Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (str): Type of conversion selected by the user.
    value (float): The numeric value to convert.

    Returns:
    float: Converted value.
    """

    if conversion_type == "1":
        return value * 3.28084   # meters to feet
    elif conversion_type == "2":
        return value / 3.28084   # feet to meters
    elif conversion_type == "3":
        return value * 2.20462   # kg to pounds
    elif conversion_type == "4":
        return value / 2.20462   # pounds to kg
    elif conversion_type == "5":
        return value * 0.264172  # liters to gallons
    elif conversion_type == "6":
        return value / 0.264172  # gallons to liters
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = input("Choose conversion type (1-6): ")

    try:
        value = float(input("Enter the value to convert: "))
        result = convert_units(choice, value)

        if result is None:
            print("Invalid conversion type selected.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Error: Please enter a valid numeric value.")


main()

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 2
Enter the value to convert: 3
Converted value: 0.914399970739201


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(numbers):
    """
    Returns the sum of numbers in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of numbers in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average value.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Returns the maximum value from the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Maximum value.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Returns the minimum value from the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Minimum value.
    """
    return min(numbers)


def main():
    print("Mathematical Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Select operation (1-4): ")

    try:
        numbers_input = input("Enter numbers separated by space: ")
        numbers = list(map(float, numbers_input.split()))

        if len(numbers) == 0:
            raise ValueError("List cannot be empty")

        if choice == "1":
            print("Sum:", find_sum(numbers))
        elif choice == "2":
            print("Average:", find_average(numbers))
        elif choice == "3":
            print("Maximum:", find_maximum(numbers))
        elif choice == "4":
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numbers.")


main()

Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Select operation (1-4): 3
Enter numbers separated by space: 4
Maximum: 4.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """Return every other element from the list starting from the first element."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6, 7, 8]))

[1, 3, 5, 7]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """Return a sublist from index start to end (inclusive)."""
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """Return the reversed version of the list using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """Return a list without the first and last elements."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """Return the first n elements of the list."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """Return the last n elements of the list."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """Return every second element starting from the second-to-last element moving backward."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """Flatten a nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """Return element from nested list using given indices."""
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst, [1,2]))

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """Return sum of all numbers in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """Remove all occurrences of elem from nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]], 2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """Return maximum element in nested list."""
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """Count how many times elem appears in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]], 2))

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """Flatten deeply nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """Return average of all elements in nested list."""
    flat = flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[7.7199629e-316 0.0000000e+000]
 [5.9040845e-321 1.7626229e-312]]


2. Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((6,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
full_array = np.full((3,3), 5)
print(full_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
zeros_like_array = np.zeros_like(full_array)
print(zeros_like_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_array = np.ones_like(full_array)
print(ones_like_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]

numpy_array = np.array(new_list)

print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr = np.arange(10,60)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
arr = np.random.random(30)
print(arr)

print("Mean:", arr.mean())

[0.91570527 0.77180009 0.79445444 0.10750629 0.11538334 0.94931683
 0.55840745 0.58793215 0.16800284 0.07824673 0.60851622 0.10213614
 0.72059315 0.28145496 0.03664644 0.88525787 0.25772984 0.77834308
 0.5205701  0.77918082 0.03784735 0.7350744  0.73935802 0.72815818
 0.96594448 0.33336797 0.45422302 0.97762686 0.02488197 0.65598811]
Mean: 0.5223218136490008


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
arr = np.random.random((10,10))

print("Array:\n", arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

Array:
 [[0.21121729 0.62864017 0.59996194 0.63853847 0.39213067 0.48667202
  0.21023864 0.64344577 0.57252598 0.67534703]
 [0.04332013 0.52801493 0.52142198 0.46693616 0.83460978 0.40739032
  0.4453083  0.47734139 0.68779953 0.40521476]
 [0.60020022 0.31394189 0.82006013 0.36740654 0.28582347 0.10949026
  0.97426116 0.4638185  0.01282626 0.7900779 ]
 [0.81742782 0.21266418 0.48202569 0.67966618 0.34502456 0.82153194
  0.86680121 0.89773102 0.1394054  0.16816242]
 [0.27125404 0.50141156 0.485516   0.94490323 0.45282588 0.28068563
  0.26872175 0.31083645 0.42103854 0.77889216]
 [0.49695984 0.88387036 0.96381417 0.50001699 0.34997046 0.32927939
  0.12475251 0.5444079  0.71346381 0.83606362]
 [0.22115974 0.34720578 0.91216164 0.30089398 0.2286257  0.48510562
  0.76934541 0.79422215 0.66888381 0.87662021]
 [0.05925575 0.21898854 0.6252452  0.0377001  0.13951573 0.6316579
  0.3722544  0.12478951 0.95448944 0.64945753]
 [0.97565711 0.46855533 0.62776524 0.12300383 0.11332039 0.85834332
  0.0

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
arr = np.zeros(10)

arr[4] = 1   # index starts from 0

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1,2,0,0,4,0])

reverse = arr[::-1]

print(reverse)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr = np.zeros((8,8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.

In [ ]:
print("Addition:")
print(x + y)

Addition:
[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
print("Subtraction:")
print(x - y)

Subtraction:
[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
print("Multiply x by 3:")
print(x * 3)

Multiply x by 3:
[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
print("Square of x:")
print(x ** 2)

Square of x:
[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
print("Dot product of v and w:")
print(np.dot(v,w))

Dot product of v and w:
219


In [ ]:
print("Dot product of x and y:")
print(np.dot(x,y))

Dot product of x and y:
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
print("Concatenate x and y (row):")
print(np.concatenate((x,y), axis=0))

Concatenate x and y (row):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
print("Concatenate v and w (column):")
print(np.column_stack((v,w)))

Concatenate v and w (column):
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
np.concatenate((x,v))

This gives an error.

Reason

x is a 2-dimensional array (2×2 matrix)

v is a 1-dimensional array (vector)

NumPy cannot concatenate arrays with different dimensions.

✔ To fix it, convert v into a 2D array:

In [ ]:
v2 = v.reshape(1,2)
print(np.concatenate((x,v2), axis=0))

[[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A^-1:\n", result)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


3. Prove (AB)

T = BTAT

In [ ]:
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T =\n", left)
print("B^T A^T =\n", right)

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
